package org.yearup.world.data;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import org.yearup.world.models.City;

import javax.sql.DataSource;
import java.sql.*;
import java.util.ArrayList;
import java.util.List;

@Component
public class MySqlCityDao implements CityDao
{
    private DataSource dataSource;

    @Autowired
    public MySqlCityDao(DataSource dataSource)
    {
        this.dataSource = dataSource;
    }

    @Override
    public List<City> searchByCountry(String country)
    {
        List<City> cities = new ArrayList<>();

        String sql = """
                SELECT ID
                    , Name
                    , CountryCode
                    , District
                    , Population
                FROM city
                WHERE CountryCode = ?;
                """;

        try(Connection connection = dataSource.getConnection();
            PreparedStatement statement = connection.prepareStatement(sql)
        )
        {
            statement.setString(1, country);

            ResultSet row = statement.executeQuery();

            // use WHILE when you expect multiple rows
            while (row.next())
            {
                int id = row.getInt("ID");
                String name = row.getString("Name");
                String countryCode = row.getString("CountryCode");
                String state = row.getString("District");
                int population = row.getInt("Population");

                City product = new City()
                {{
                    setId(id);
                    setName(name);
                    setCountry(countryCode);
                    setState(state);
                    setPopulation(population);
                }};

                cities.add(product);
            }

        }
        catch (SQLException e)
        {
            System.out.println();
            System.out.println(e.getMessage());
            System.out.println();
        }

        return cities;

    }

    @Override
    public City getById(int cityId)
    {
        String sql = """
                SELECT ID
                    , Name
                    , CountryCode
                    , District
                    , Population
                FROM city
                WHERE ID = ?;
                """;

        try(Connection connection = dataSource.getConnection();
            PreparedStatement statement = connection.prepareStatement(sql)
        )
        {
            statement.setInt(1, cityId);

            ResultSet row = statement.executeQuery();

            // use WHILE when you expect multiple rows
            while (row.next())
            {
                int id = row.getInt("ID");
                String name = row.getString("Name");
                String country = row.getString("CountryCode");
                String state = row.getString("District");
                int population = row.getInt("Population");

                City city = new City()
                {{
                    setId(id);
                    setName(name);
                    setCountry(country);
                    setState(state);
                    setPopulation(population);
                }};

                return city;
            }

        }
        catch (SQLException e)
        {
            System.out.println();
            System.out.println(e.getMessage());
            System.out.println();
        }

        return null;
    }

    @Override
    public City add(City city)
    {
        String sql = """
                INSERT INTO city (Name, CountryCode, District, Population)
                VALUES (?, ?, ?, ?);
                """;

        try(Connection connection = dataSource.getConnection();
            PreparedStatement statement = connection.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)
        )
        {
            statement.setString(1, city.getName());
            statement.setString(2, city.getCountry());
            statement.setString(3, city.getState());
            statement.setInt(4, city.getPopulation());

            statement.executeUpdate();

            // auto incremented keys are returned in a ResultSet
            try(ResultSet key = statement.getGeneratedKeys())
            {
                if(key.next())
                {
                    // get the first (and only) column value
                    // this is the new productId - that was generated by the db
                    int cityId = key.getInt(1);
                    return getById(cityId);
                }
            }
            catch(Exception ignored){}

        }
        catch (SQLException e)
        {
            System.out.println();
            System.out.println(e.getMessage());
            System.out.println();
        }

        return null;
    }

    @Override
    public void update(int id, City city) throws SQLException
    {

        String sql = """
                UPDATE city
                SET Name = ?
                    , CountryCode = ?
                    , District = ?
                    , Population = ?
                WHERE ID = ?;
                """;

        try(Connection connection = dataSource.getConnection();
            PreparedStatement statement = connection.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)
        )
        {
            statement.setString(1, city.getName());
            statement.setString(2, city.getCountry());
            statement.setString(3, city.getState());
            statement.setInt(4, city.getPopulation());
            statement.setInt(5, id);

            statement.executeUpdate();

        }
        catch (SQLException e)
        {
            throw e;
        }
    }

    @Override
    public void delete(int id) throws SQLException
    {

        String sql = """
                DELETE FROM city
                WHERE ID = ?;
                """;

        try(Connection connection = dataSource.getConnection();
            PreparedStatement statement = connection.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)
        )
        {
            statement.setInt(1, id);

            statement.executeUpdate();

        }
        catch (SQLException e)
        {
            throw e;
        }
    }
}
